/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        background: "var(--color-background)",
        surface: "var(--color-surface)",
        "surface-secondary": "var(--color-surface-secondary)",
        "surface-overlay": "var(--color-surface-overlay)",
        border: "var(--color-border)",
        primary: "var(--color-text-primary)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-tertiary": "var(--color-text-tertiary)",
        "storage-used": "var(--color-storage-used)",
        "storage-free": "var(--color-storage-free)",
        "btn-primary-bg": "var(--color-btn-primary-bg)",
        "btn-primary-text": "var(--color-btn-primary-text)",
        "btn-secondary-border": "var(--color-btn-secondary-border)",
        "tag-safe-text": "var(--color-tag-safe-text)",
        "tag-safe-bg": "var(--color-tag-safe-bg)",
        "tag-check-text": "var(--color-tag-check-text)",
        "tag-check-bg": "var(--color-tag-check-bg)",
        "tag-danger-text": "var(--color-tag-danger-text)",
        "tag-danger-bg": "var(--color-tag-danger-bg)",
        "tag-unsure-text": "var(--color-tag-unsure-text)",
        "tag-unsure-bg": "var(--color-tag-unsure-bg)",
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        rounded: ["var(--font-rounded)"],
      },
      fontSize: {
        title: ["var(--text-title)", { lineHeight: "var(--text-title--line-height)", fontWeight: "var(--text-title--font-weight)" }],
        row: ["var(--text-row)", { lineHeight: "var(--text-row--line-height)", fontWeight: "var(--text-row--font-weight)" }],
        meta: ["var(--text-meta)", { lineHeight: "var(--text-meta--line-height)", fontWeight: "var(--text-meta--font-weight)" }],
        "meta-emphasis": ["var(--text-meta-emphasis)", { lineHeight: "var(--text-meta-emphasis--line-height)", fontWeight: "var(--text-meta-emphasis--font-weight)" }],
      },
      spacing: {
        0: "var(--spacing-0)",
        1: "var(--spacing-1)",
        2: "var(--spacing-2)",
        3: "var(--spacing-3)",
        4: "var(--spacing-4)",
        5: "var(--spacing-5)",
        6: "var(--spacing-6)",
        7: "var(--spacing-7)",
        8: "var(--spacing-8)",
        9: "var(--spacing-9)",
        10: "var(--spacing-10)",
        11: "var(--spacing-11)",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
      },
    },
  },
};
